### ISSUE TITLE
Bug: "关于"页面信息有误

### ISSUE THREAD

**Issue by smy1999** [yuxiaoyuan0406/yuxiaoyuan0406.github.io#14]
关于页面信息有误
1.语言中图片无法加载
2."关于"页面与博文页面的个人信息中名称不一致
望早日修改

**Comment by smy1999** [comment]
语言那里还是有问题啊

**Comment by yuxiaoyuan0406** [comment]
> 关于页面信息有误 1.语言中图片无法加载 2."关于"页面与博文页面的个人信息中名称不一致 望早日修改

Problem 1 comes from user's internet connection, which is un-fixable by me.

Problem 2 is fixed, thank you for your support. 

Have a nice day!
